import { WeaponDef } from '../types';

export const WEAPON_REGISTRY: Record<string, WeaponDef> = {
  mp5_tactical: {
    id: 'mp5_tactical',
    name: 'MP-5X Tactical',
    category: 'cqb',
    damage: 24,
    fireRate: 13.5, // ~810 RPM
    magazineSize: 30,
    reloadTime: 1.4,
    spread: 0.02,
    recoil: 0.016,
    range: 65,
    zoomFov: 58,
    isHitscan: true,
    color: '#e2e8f0', // Ballistic bullet tracer (steel white/yellow)
    beamType: 'ion',
    description: 'Precision roller-delayed 9mm submachine gun featuring a curved 30-round box magazine, hooded front sight, and lightning-fast cyclic fire.',
    unlockedAtLevel: 1,
  },
  mp40_sturm: {
    id: 'mp40_sturm',
    name: 'Maschine-40',
    category: 'cqb',
    damage: 32,
    fireRate: 9.0, // ~540 RPM
    magazineSize: 32,
    reloadTime: 1.7,
    spread: 0.018,
    recoil: 0.022,
    range: 60,
    zoomFov: 60,
    isHitscan: true,
    color: '#fef08a', // Vintage warm brass tracer
    beamType: 'pulse',
    description: 'Stamped-steel submachine gun with a vertical stick magazine and underfolding skeleton stock. Rhythmic, steady, and high kinetic impact.',
    unlockedAtLevel: 1,
  },
  pulse_carbine: {
    id: 'pulse_carbine',
    name: 'Pulse Carbine',
    category: 'assault',
    damage: 26,
    fireRate: 8.5,
    magazineSize: 30,
    reloadTime: 1.6,
    spread: 0.015,
    recoil: 0.02,
    range: 120,
    zoomFov: 55,
    isHitscan: true,
    color: '#06b6d4', // Cyan
    beamType: 'pulse',
    description: 'Rapid-fire energy assault rifle designed for versatile medium-range skirmishes with steady recoil compensation.',
    unlockedAtLevel: 1,
  },
  arc_blaster: {
    id: 'arc_blaster',
    name: 'Arc Blaster',
    category: 'cqb',
    damage: 42,
    fireRate: 4.2,
    magazineSize: 18,
    reloadTime: 1.8,
    spread: 0.035,
    recoil: 0.035,
    range: 55,
    zoomFov: 62,
    isHitscan: true,
    color: '#38bdf8', // Sky blue
    beamType: 'arc',
    description: 'Discharges concentrated electric arcs that instantly electrify targets with high kinetic stopping power.',
    unlockedAtLevel: 2,
  },
  vortex_rifle: {
    id: 'vortex_rifle',
    name: 'Vortex Rifle',
    category: 'sniper',
    damage: 88,
    fireRate: 1.1,
    magazineSize: 6,
    reloadTime: 2.3,
    spread: 0.002,
    recoil: 0.07,
    range: 250,
    zoomFov: 32,
    isHitscan: true,
    color: '#c084fc', // Violet
    beamType: 'rail',
    description: 'Heavy magnetic coil sniper rifle delivering devastating hyper-velocity penetrator rounds across open arenas.',
    unlockedAtLevel: 3,
  },
  ion_smg: {
    id: 'ion_smg',
    name: 'Ion SMG',
    category: 'cqb',
    damage: 16,
    fireRate: 14.0,
    magazineSize: 42,
    reloadTime: 1.3,
    spread: 0.04,
    recoil: 0.018,
    range: 45,
    zoomFov: 65,
    isHitscan: true,
    color: '#10b981', // Emerald green
    beamType: 'ion',
    description: 'Ultra high-cyclic rate submachine gun firing superheated ion pellets for room-clearing dominance.',
    unlockedAtLevel: 4,
  },
  plasma_launcher: {
    id: 'plasma_launcher',
    name: 'Plasma Launcher',
    category: 'heavy',
    damage: 90,
    fireRate: 0.9,
    magazineSize: 4,
    reloadTime: 2.7,
    spread: 0.02,
    recoil: 0.08,
    range: 90,
    zoomFov: 60,
    isHitscan: false,
    projectileSpeed: 38,
    splashRadius: 5.5,
    color: '#f97316', // Orange
    beamType: 'plasma',
    description: 'Fires volatile plasma orbs that detonate on impact with immense concussive force and thermal shockwaves.',
    unlockedAtLevel: 5,
  },
  phase_pistol: {
    id: 'phase_pistol',
    name: 'Phase Pistol',
    category: 'sidearm',
    damage: 28,
    fireRate: 6.0,
    magazineSize: 15,
    reloadTime: 1.1,
    spread: 0.02,
    recoil: 0.025,
    range: 65,
    zoomFov: 68,
    isHitscan: true,
    color: '#f59e0b', // Amber
    beamType: 'pulse',
    description: 'Lightweight sidearm utilizing phase-shifted pulses. Instantaneous weapon draw and snappy handling.',
    unlockedAtLevel: 1,
  },
};

export const WEAPON_SKINS = [
  { id: 'skin_default', name: 'Standard Issue', primary: '#334155', accent: '#38bdf8', price: 0, level: 1 },
  { id: 'skin_obsidian', name: 'Obsidian Stealth', primary: '#0f172a', accent: '#64748b', price: 600, level: 2 },
  { id: 'skin_solar', name: 'Solar Flare', primary: '#7c2d12', accent: '#f97316', price: 1200, level: 4 },
  { id: 'skin_neon_grid', name: 'Cyber Matrix', primary: '#1e1b4b', accent: '#06b6d4', price: 2000, level: 6 },
  { id: 'skin_gold_apex', name: 'Apex Champion Gold', primary: '#78350f', accent: '#fbbf24', price: 3500, level: 8 },
];
